//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_ventas
    {
        public int cod_detalle { get; set; }
        public int cod_ventas { get; set; }
        public int cod_producto { get; set; }
        public int cantidad { get; set; }
        public long precio_producto { get; set; }
        public long subtotal { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Ventas Ventas { get; set; }

        public override string ToString()
        {
            return string.Format(" Cantidad:{0} | Subtotal:{1}", this.cantidad,this.subtotal);
        }
    }
}
