//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle_compra = new HashSet<Detalle_compra>();
            this.Detalle_ventas = new HashSet<Detalle_ventas>();
        }
    
        public int cod_producto { get; set; }
        public string nom_producto { get; set; }
        public string categoria { get; set; }
        public long precio_compra { get; set; }
        public long precio_venta { get; set; }
        public int stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_compra> Detalle_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_ventas> Detalle_ventas { get; set; }

        public override string ToString()
        {
            return string.Format("Nombre:{0} | Categoria:{1} | Precio C:{2} | Stock:{3}", this.nom_producto, this.categoria, this.precio_compra, this.stock);
        }
    }
}
