//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.Detalle_ventas = new HashSet<Detalle_ventas>();
        }
    
        public int cod_venta { get; set; }
        public Nullable<int> cod_cliente { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public long total { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_ventas> Detalle_ventas { get; set; }

        public override string ToString()
        {
            return string.Format("Fecha:{0} | Total:{1} ",this.fecha_venta, this.total);
        }
    }
}
